### ISSUE TITLE
Unable to resolve local relative file references

### ISSUE THREAD

**Issue by CloudNiner** [ikalnytskyi/sphinxcontrib-openapi#3]
I have two yml files that define my Swagger specification:
```
# api_spec.yml
...
paths:
  /foo:
    get:
      summary: Foo List
      description: Lists all foos
      produces:
        - application/json
      responses:
        "200":
          description: A list of Foo objects
          schema:
            type: array
            items:
              $ref: ./definitions/foo.yml#/Foo
...
```
and
```
# definitions/foo.yml
Foo:
  type: object
  properties:
    id:
      type: string
      description: Unique id for foo
    label:
      type: string
      description: Human-readable description of foo
```

When I attempt to build my sphinx docs, I get the following error:
```
building [html]: targets for 13 source files that are out of date
updating environment: 13 added, 0 changed, 0 removed
reading sources... [  7%] api_reference                                                                                                           
Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 346, in resolve_from_url
    raise RefResolutionError(exc)
RefResolutionError: unknown url type: ./definitions/scenario.yml
The full traceback has been saved in /tmp/sphinx-err-7U659m.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:58: recipe for target 'html' failed
make: *** [html] Error 1
```

It appears that `jsonschema.RefResolver` is always instantiated with `base_uri = ''`, which would break local refs. Is it possible to have an option on the openapi directive that would allow local file refs in the Swagger definition somehow?

It appears that some workarounds are being explored here: https://github.com/Julian/jsonschema/issues/313#issuecomment-268283198
